version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  car:
    image: antonidass/rsoi2-car-service:latest
    container_name: car
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8070:8070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cars
      - SPRING_DATASOURCE_USERNAME=program
      - SPRING_DATASOURCE_PASSWORD=test

  payment:
    image: antonidass/rsoi2-payment-service:latest
    container_name: payment
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8050:8050"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payments
      - SPRING_DATASOURCE_USERNAME=program
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka:9092

  rental:
    image: antonidass/rsoi2-rental-service:latest
    container_name: rental
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8060:8060"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rentals
      - SPRING_DATASOURCE_USERNAME=program
      - SPRING_DATASOURCE_PASSWORD=test
      - GW=http://gw:8080/api/v1

  gw:
    image: antonidass/rsoi2-gateway-service:latest
    container_name: gateway_serivce
    depends_on:
      - rental
      - car
      - payment
    ports:
      - "8080:8080"
    environment:
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9092
      - CAR=http://car:8070
      - PAYMENT=http://payment:8050
      - RENTAL=http://rental:8060

volumes:
  db-data:
